### ISSUE TITLE
Typo in cuttables.lua

### ISSUE THREAD

**Issue by axcore** [t-affeldt/sickles#6]
`sickles.register_cuttable("ethereal:crystal_dirt", "default:dirt", "ethereal:crytalgrass")`

The letter S is missing, the last item should be `ethereal:crystalgrass`.

`sickles.register_cuttable("ethereal:grovel_dirt", "default:dirt", "sickles:moss")`

That should be `ethereal:grove_dirt`

**Comment by FloraMaeWolfe** [comment]
Since it seems this dev has abandoned this project, I went ahead and fixed the typos here:
https://gitlab.com/validandloved/sickles

since I use it on my server.

**Comment by t-affeldt** [comment]
Thank you. Fixed.
